version: "3"
# 管理的服务
services:
  redis:
    # 指定镜像
    #image: redis:4
    image: redis:6.0.4-alpine3.11
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      - "${REDIS_DIR}/conf:/usr/local/etc/redis"
      - "${REDIS_DIR}/data:/data"
      - "/etc/localtime:/etc/localtime"
    command:
      # 执行的命令
      redis-server /usr/local/etc/redis/redis.conf

  mysql:
    image: mysql:5.7.30
    ports:
      - 3306:3306
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
      #- "${MYSQL_DIR}/binlogs:/var/lib/mysql/binlogs/mysql-bin"
      - "/etc/localtime:/etc/localtime"
    environment:
      # 环境变量
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
