version: '2.2'
services:
  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://192.168.11.125:9200

  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    #image:  elasticsearch:7.4.2
    image: zhangguanzhang/docker.elastic.co.elasticsearch.elasticsearch:7.4.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=dg-elk
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4096m
    cap_add:
      - IPC_LOCK
    volumes:
      #- esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/package:/tmp/package
    user: elasticsearch
    #user: root
    #command: bash -c "/bin/echo -e 'y'|elasticsearch-plugin install file:///tmp/package/elasticsearch-analysis-ik-7.4.2.zip; elasticsearch;echo 262144 > /proc/sys/vm/max_map_count"
    command: bash -c "/bin/echo -e 'y'|elasticsearch-plugin install file:///tmp/package/elasticsearch-analysis-ik-7.4.2.zip; elasticsearch"
    hostname: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    #image: kibana:7.4.2
    image: zhangguanzhang/docker.elastic.co.kibana.kibana:7.4.2
    container_name: kibana
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    hostname: kibana
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - "5601:5601"



  logstash:
    image: zhangguanzhang/docker.elastic.co.logstash.logstash:7.4.2
    container_name: logstash
    hostname: logstash
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 9600:9600
      - 5044:5044
#volumes:
#  esdata:
#    driver: local
